apiVersion: v1
kind: Service
metadata:
  name: assignment-api-service
  labels:
    app: assignment-api
spec:
  type: NodePort
  selector:
    app: assignment-api
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
